name: "Test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: |
          docker run --rm -v "${PWD}:${PWD}" -w "${PWD}" kmaehashi/xojo-docker:xojo2022r11-ubuntu20.04 ./.github/workflows/test.sh
